### ISSUE TITLE
Error downloading subtitles from "Open Subtitles"

### ISSUE THREAD

**Issue by g9420** [jellyfin/jellyfin-plugin-opensubtitles#25]
```
[2019-12-22 12:01:27.500 +00:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
```

**Comment by AllirionX** [comment]
I had the same problem. I changed my opensubtitles password from `m_zb%33!wQM(pL3(Dl@l` to alphanumeric characters only and that solved the problem.

**Comment by ikomhoog** [comment]
I already had my password be alphanumeric, but I missed the capitalization of my username.
My guess is that this error comes up when the wrong credentials are filled in.

This should be fixed by completing: https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/24 which asks for a login test button.

**Comment by daddy32** [comment]
Hmm I'm pretty sure I'm entering correct name and password, including case, not including special characters, and yet still getting error (similar, but differend - see below; mentioned in #5162).
I also confirmed the login credentials and ability to download the subtitles on the site itself. Let's see what #24 brings.

Error:

```
[2021-05-30 11:04:20.519 +02:00] [ERR] [44] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"         
System.Xml.XmlException: The 'hr' start tag on line 6 position 2 does not match the end tag of 'body'. Line 7, position 3.                              
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)                                                                                                   
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)                                                                                  
   at System.Xml.XmlTextReaderImpl.ParseEndElement()                                                                                                    
   at System.Xml.XmlTextReaderImpl.ParseElementContent()                                                                                                
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)                                                                            
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)             
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)                                                   
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)                   
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)              
```

**Comment by abienz** [comment]
I'm also getting this issue, and I have alphanumeric username and alphanumeric password.

**Comment by syntapse** [comment]
Same issue, not sure how to get it working.

**Comment by the-lazy-fox** [comment]
Same issue here

**Comment by 7system7** [comment]
Same issue here
